module.exports = [
  {
    itemId: 1,
    name: "Raw karambwanji",
    level: 1,
    experience: 10.6,
    member: true,
    imageUrl: "https://runescape.wiki/images/Raw_karambwanji.png?02510",
  },
  {
    itemId: 2,
    name: "Raw shrimps",
    level: 1,
    experience: 31.8,
    member: false,
    imageUrl: "https://runescape.wiki/images/Raw_shrimps.png?575eb",
  },
  {
    itemId: 3,
    name: "Raw anchovies",
    level: 1,
    experience: 31.8,
    member: false,
    imageUrl: "https://runescape.wiki/images/Raw_anchovies.png?4cd31",
  },
  {
    itemId: 4,
    name: "Raw minnow",
    level: 1,
    experience: 31.8,
    member: false,
    imageUrl: "https://runescape.wiki/images/Raw_minnow.png?0c1ff",
  },
  {
    itemId: 5,
    name: "Raw crayfish",
    level: 1,
    experience: 31.8,
    member: false,
    imageUrl: "https://runescape.wiki/images/Raw_crayfish.png?3c61f",
  },
  {
    itemId: 6,
    name: "Raw sardine",
    level: 1,
    experience: 42.5,
    member: false,
    imageUrl: "https://runescape.wiki/images/Raw_sardine.png?604e8",
  },
  {
    itemId: 7,
    name: "Raw karambwan",
    level: 1,
    experience: 201.4,
    member: true,
    imageUrl: "https://runescape.wiki/images/Raw_karambwan.png?eef09",
    altName: "Hello, it is me A Friend",
  },
  {
    itemId: 8,
    name: "Raw herring",
    level: 5,
    experience: 53,
    member: false,
    imageUrl: "https://runescape.wiki/images/Raw_herring.png?ee947",
  },
  {
    itemId: 9,
    name: "Raw mackerel",
    level: 10,
    experience: 31.8,
    member: false,
    imageUrl: "https://runescape.wiki/images/Raw_mackerel.png?38816",
  },
  {
    itemId: 10,
    name: "Raw trout",
    level: 15,
    experience: 74.2,
    member: true,
    imageUrl: "https://runescape.wiki/images/Raw_trout.png?4efd3",
  },
  {
    itemId: 11,
    name: "Raw cod",
    level: 18,
    experience: 79.5,
    member: true,
    imageUrl: "https://runescape.wiki/images/Raw_cod.png?95ab4",
  },
  {
    itemId: 12,
    name: "Raw pike",
    level: 20,
    experience: 84.8,
    member: false,
    imageUrl: "https://runescape.wiki/images/Raw_pike.png?a1ee3",
  },
  {
    itemId: 13,
    name: "Raw salmon",
    level: 25,
    experience: 95.4,
    member: false,
    imageUrl: "https://runescape.wiki/images/Raw_salmon.png?ab536",
  },
  {
    itemId: 14,
    name: "Slimy eel",
    level: 28,
    experience: 100.7,
    member: true,
    imageUrl: "https://runescape.wiki/images/Slimy_eel.png?3e4b8",
  },
  {
    itemId: 15,
    name: "Raw tuna",
    level: 30,
    experience: 106,
    member: false,
    imageUrl: "https://runescape.wiki/images/Raw_lobster.png?57ddd",
  },
  {
    itemId: 16,
    name: "Raw rainbow fish",
    level: 35,
    experience: 116.6,
    member: true,
    imageUrl: "https://runescape.wiki/images/Raw_rainbow_fish.png?e0f27",
  },
  {
    itemId: 17,
    name: "Raw cave eel",
    level: 38,
    experience: 121.9,
    member: true,
    imageUrl: "https://runescape.wiki/images/Raw_cave_eel.png?77026",
  },
  {
    itemId: 18,
    name: "Raw lobster",
    level: 40,
    experience: 172.2,
    member: false,
    imageUrl: "https://runescape.wiki/images/Raw_lobster.png?57ddd",
  },
  {
    itemId: 19,
    name: "Raw bass",
    level: 43,
    experience: 137.8,
    member: true,
    imageUrl: "https://runescape.wiki/images/Raw_bass.png?04af1",
  },
  {
    itemId: 20,
    name: "Raw swordfish",
    level: 45,
    experience: 148.4,
    member: false,
    imageUrl: "https://runescape.wiki/images/Raw_swordfish.png?2bf97",
  },
  {
    itemId: 21,
    name: "Raw desert sole",
    level: 52,
    experience: 151.1,
    member: true,
    imageUrl: "https://runescape.wiki/images/Raw_desert_sole.png?e9b22",
  },
  {
    itemId: 22,
    name: "Raw lava eel",
    level: 53,
    experience: 31.8,
    member: true,
    imageUrl: "https://runescape.wiki/images/Raw_lava_eel.png?4f671",
    altName: "This doesn't make any sense at all",
  },
  {
    itemId: 23,
    name: "Raw catfish",
    level: 60,
    experience: 153.7,
    member: true,
    imageUrl: "https://runescape.wiki/images/Raw_catfish.png?a5482",
  },
  {
    itemId: 24,
    name: "Raw monkfish",
    level: 64,
    experience: 159,
    member: true,
    imageUrl: "https://runescape.wiki/images/Raw_monkfish.png?ef04c",
  },
  {
    itemId: 25,
    name: "Raw beltfish",
    level: 72,
    experience: 174.9,
    member: true,
    imageUrl: "https://runescape.wiki/images/Raw_beltfish.png?f0df9",
  },
  {
    itemId: 26,
    name: "Raw blubber jellyfish",
    level: 72,
    experience: 174.9,
    member: true,
    imageUrl:
      "https://runescape.wiki/images/Raw_green_blubber_jellyfish.png?1ee03",
  },
  {
    itemId: 27,
    name: "Raw shark",
    level: 80,
    experience: 222.6,
    member: true,
    imageUrl: "https://runescape.wiki/images/Raw_sea_turtle.png?cacbf",
  },
  {
    itemId: 28,
    name: "Raw sea turtle",
    level: 82,
    experience: 224,
    member: true,
    imageUrl: "https://runescape.wiki/images/Raw_sea_turtle.png?cacbf",
  },
  {
    itemId: 29,
    name: "Raw geat white shark",
    level: 84,
    experience: 224.7,
    member: true,
    imageUrl: "https://runescape.wiki/images/Raw_great_white_shark.png?7ac63",
  },
  {
    itemId: 30,
    name: "Fish oil from raw tarpon",
    level: 91,
    experience: 127.2,
    member: true,
    imageUrl: "https://runescape.wiki/images/Raw_tarpon.png?3e309",
  },
  {
    itemId: 32,
    name: "Fish oil from raw sillago",
    level: 91,
    experience: 127.2,
    member: true,
    imageUrl: "https://runescape.wiki/images/Raw_sillago.png?06638",
  },
  {
    itemId: 33,
    name: "Fish oil from raw seerfish",
    level: 91,
    experience: 127.2,
    member: true,
    imageUrl: "https://runescape.wiki/images/Raw_seerfish.png?a0331",
  },
  {
    itemId: 34,
    name: "Raw manta ray",
    level: 91,
    experience: 229.3,
    member: true,
    imageUrl: "https://runescape.wiki/images/Raw_manta_ray.png?969c4",
  },
  {
    itemId: 35,
    name: "Raw rocktail",
    level: 93,
    experience: 238.5,
    member: true,
    imageUrl: "https://runescape.wiki/images/Raw_rocktail.png?f05cc",
  },
  {
    itemId: 36,
    name: "Raw tiger shark",
    level: 95,
    experience: 243.8,
    member: true,
    imageUrl: "https://runescape.wiki/images/Raw_tiger_shark.png?b887b",
  },
  {
    itemId: 37,
    name: "Raw blubber jellyfish",
    level: 95,
    experience: 249.1,
    member: true,
    imageUrl:
      "https://runescape.wiki/images/Raw_blue_blubber_jellyfish.png?83f73",
  },
  {
    itemId: 38,
    name: "Raw wobbegong",
    level: 96,
    experience: 254.4,
    member: true,
    imageUrl: "https://runescape.wiki/images/Raw_wobbegong.png?e1d81",
  },
  {
    itemId: 39,
    name: "Raw sailfish",
    level: 99,
    experience: 286.2,
    member: true,
    imageUrl: "https://runescape.wiki/images/Raw_sailfish.png?6f620",
  },
];
